### ISSUE TITLE
MOI Optimizer

### ISSUE THREAD

**Issue by blegat** [JuliaSmoothOptimizers/NLPModelsJuMP.jl#152]
I am wondering whether it would be possible to make something like this work
```julia
model = Model(NLPModelsJuMP.Optimizer)
set_attribute(model, "solver", percival)
# ...
optimize!(model)
```
For this, we would need to parse the whole model at the MOI level but looking at the code, it doesn't seem to hard to change this.

- [x] https://github.com/JuliaSmoothOptimizers/NLPModelsJuMP.jl/pull/153
- [x] https://github.com/JuliaSmoothOptimizers/NLPModelsJuMP.jl/pull/155

Let me know what you think.

**Comment by amontoison** [comment]
I like the idea @blegat!
