### ISSUE TITLE
Retroactively add an upper bound to JuMP to older versions of NLPModelsJuMP 

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/NLPModelsJuMP.jl#163]
This bound:

JuMP = "1.2 - 1.14.1"

I'm looking into this.

**Comment by odow** [comment]
What parts broke?

**Comment by amontoison** [comment]
> What parts broke?

https://github.com/JuliaSmoothOptimizers/NLPModelsJuMP.jl/issues/160#issue-1905794494

**Comment by odow** [comment]
But this is a new feature. It wouldn't have worked on older versions

**Comment by abelsiqueira** [comment]
Hum, you're right that it is not strictly necessary since we don't have to support the new features, but I am worried about the long term when the new syntax is used frequently enough if we still don't support it. Hopefully, it will be an easy fix and we won't have to worry about it. Let me take a look at it this morning.

**Comment by abelsiqueira** [comment]
Looking at it this morning, I could not find a way to add support JuMP 1.15.0.
I've been far from the code for too long and nothing is familiar to me anymore, so I don't even understand our code base anymore.

**Comment by abelsiqueira** [comment]
I decided against adding the bounds. Will make a new release to avoid changing the registry directly. Issue #160 deals with the missing features of JuMP 1.15.0
