### ISSUE TITLE
Linear / quadratic models

### ISSUE THREAD

**Issue by amontoison** [JuliaSmoothOptimizers/NLPModelsJuMP.jl#49]
If a JuMP model `m` has linear constraints +  linear or quadratic objective, we cannot use `NLPEvalaluator(m).constraints` because it's an undefined reference. We can detect if we have non linear objective with `eval.has_nlobj` but I don't know if we have something similar for non linear constraints...

Edit :`num_nl_constraints(m)` works.

**Comment by dpo** [comment]
🙀
