### ISSUE TITLE
SingleVariable constraints

### ISSUE THREAD

**Issue by amontoison** [JuliaSmoothOptimizers/NLPModelsJuMP.jl#64]
It's possible to encouter SingleVariable constraints if we define in the same time the variable and the constraint.
```
m = Model()
@variable(m, t >= 1)
@variable(m, s == 2)
```
I should remove this line https://github.com/JuliaSmoothOptimizers/NLPModelsJuMP.jl/blob/master/src/utils.jl#L165 and add a function `parser_SV`.

**Comment by dpo** [comment]
The first is a bound and is ok. The second is a fixed variable. Ideally, we would have a way to preprocess those out. I don't know if JuMP can do that.

**Comment by amontoison** [comment]
I remember why https://github.com/JuliaSmoothOptimizers/NLPModelsJuMP.jl/blob/master/src/utils.jl#L165 is used and it's relevant to keep it. Fixed variables are just treated separately by JuMP. I missed this corner case.

```
m = Model()
@variable(m, t >= 1)
@variable(m, s == 2)
@variable(m, r <= -3)
@variable(m, -7 >= z >= -12)
```
```
vars = all_variables(m)

4-element Array{VariableRef,1}:
 t
 s
 r
 z
```
```
lvar = map(var -> has_lower_bound(var) ? lower_bound(var) : -Inf, vars)

4-element Array{Float64,1}:
   1.0
 -Inf
 -Inf
 -12.0
```
```
uvar = map(var -> has_upper_bound(var) ? upper_bound(var) :  Inf, vars)

4-element Array{Float64,1}:
 Inf
 Inf
  1.0
 -7.0
```
I should use `is_fixed` and `fix_value` for `s`.
```
lvar = lvar = map(var -> is_fixed(var) ? fix_value(var) : 
       (has_lower_bound(var) ? lower_bound(var) : -Inf), vars)

4-element Array{Float64,1}:
   1.0
   2.0
 -Inf
 -12.0
```
and
```
uvar = map(var -> is_fixed(var) ? fix_value(var) : 
       (has_upper_bound(var) ? upper_bound(var) :  Inf), vars)

4-element Array{Float64,1}:
 Inf
  2.0
  1.0
 -7.0
```

**Comment by dpo** [comment]
Is it possible to ask JuMP to eliminate fixed vars?

**Comment by amontoison** [comment]
I think that it should be done at the solver level and not during the modeling.

**Comment by dpo** [comment]
Can JuMP do it or not?

Preprocessing is often a separate step that is neither in the solver nor in the modeling system.

**Comment by amontoison** [comment]
I don't know...
