### ISSUE TITLE
Define MathOptNLPModel when hessian is not available

### ISSUE THREAD

**Issue by tmigot** [JuliaSmoothOptimizers/NLPModelsJuMP.jl#68]
Trying to convert the following problem in an NLPModel:
```
using JuMP, NLPModelsJuMP

  model = Model()
  @variable(model, x[1:2])
  g(x::T, y::T) where {T<:Real} = x * y
  function ∇g(g::Vector{T}, x::T, y::T) where {T<:Real}
      g[1] = y
      g[2] = x
      return
  end
  register(model, :g, 2, g, ∇g)
  @NLobjective(model, Min, g(x[1], x[2]))
  nlp = MathOptNLPModel(model)
```
will return `Unsupported feature Hess`. From what I understand in MOI, when using `register` in the model, the hessian is not available. Hence, `:Hess` and `:HessVec` are not available for such problems in `MOI.initialize`.

Any suggestion to handle this case? 
Maybe add a `try/catch` and then assume that the user won't use hess-related function.

**Comment by amontoison** [comment]
Can't you provide a function for ∇²g ?
I just need to update this line https://github.com/JuliaSmoothOptimizers/NLPModelsJuMP.jl/blob/master/src/moi_nlp_model.jl#L26 otherwise.

**Comment by tmigot** [comment]
When checking the doc of the function `JuMP.register` it is said:
```
  register(
      model::Model,
      s::Symbol,
      dimension::Integer,
      f::Function,
      ∇f::Function,
      ∇²f::Function,
  )

  Register the user-defined function f that takes dimension arguments in model as the symbol s. In addition, provide a gradient function ∇f and a hessian function
  ∇²f.

  ∇f and ∇²f must return numbers corresponding to the first- and second-order derivatives of the function f respectively.

  Notes
  =======

    •  Because automatic differentiation is not used, you can assume the inputs are all Float64.

    •  This method will throw an error if dimension > 1.

    •  s does not have to be the same symbol as f, but it is generally more readable if it is.
```
So, it doesn't seem possible to provide the hessian matrix for multivariate functions.

**Comment by amontoison** [comment]
I will on it next week @tmigot
