### ISSUE TITLE
`Function MathOptInterface.ScalarQuadraticFunction{Float64} is not supported.`

### ISSUE THREAD

**Issue by tmigot** [JuliaSmoothOptimizers/NLPModelsJuMP.jl#84]
I am suspecting this is related to #50, there is this warning in [OptimizationProblems.jl](https://github.com/JuliaSmoothOptimizers/OptimizationProblems.jl/blob/main/src/PureJuMP/hs61.jl) and the resulting NLPModel has no constraints, while the JuMP model seems to be ok.
```
using OptimizationProblems
using NLPModelsJuMP

prob = :hs61
prob_fn = eval(Meta.parse("OptimizationProblems.PureJuMP.$(prob)"))
nlp_jump = MathOptNLPModel(prob_fn())
nlp_jump.meta.ncon # is == 0
```

**Comment by tmigot** [comment]
Then, we should modifiy hs61 in OptimizationProblems.jl, no?

**Comment by amontoison** [comment]
If it's the only problem with quadratic constraints modeled with `@constraint`, yes you should update it.

**Comment by tmigot** [comment]
Cool, I will open a PR :).

**Comment by amontoison** [comment]
It's the only problem with this issue.

```
for prob in names(OptimizationProblems)
        prob == :OptimizationProblems && continue
        println(prob)
        prob_fn = eval(prob)
        model = prob_fn()
        nlp = MathOptNLPModel(model)
end
```

**Comment by tmigot** [comment]
Yes, I reviewed them in [PR 69](https://github.com/JuliaSmoothOptimizers/OptimizationProblems.jl/pull/69) and I think so.

**Comment by tmigot** [comment]
I misunderstood. This is an NLPModelsJuMP problem and not a JuMP problem, so we don't have to modify OptimizationProblems.jl.
We will have to check-in OptimizationProblems.jl that @NLconstraints are not used in cases with linear or quadratic constraints.
